-- Jalankan ini di Supabase SQL Editor

-- Tabel berita
create table news (
  id bigint generated by default as identity primary key,
  title text not null,
  cat text default 'Berita',
  body text not null,
  icon text default '📰',
  status text default 'published',
  date text,
  created_at timestamp with time zone default now()
);

-- Tabel galeri
create table gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text default '🏢',
  descr text,
  created_at timestamp with time zone default now()
);

-- Tabel layanan
create table services (
  id bigint generated by default as identity primary key,
  icon text default '🔧',
  title text not null,
  descr text not null,
  created_at timestamp with time zone default now()
);

-- Seed data awal (opsional, hapus kalau tidak mau)
insert into news (title, cat, body, icon, status, date) values
  ('Perusahaan Raih Penghargaan Nasional 2024', 'Prestasi', 'Kami dengan bangga mengumumkan bahwa perusahaan kami berhasil meraih penghargaan bergengsi sebagai perusahaan terbaik.', '🏆', 'published', '27 Jun 2025'),
  ('Pembukaan Kantor Cabang Baru', 'Pengumuman', 'Dalam rangka memperluas jangkauan layanan, kami membuka kantor cabang baru di beberapa kota besar Indonesia.', '🏢', 'published', '20 Jun 2025'),
  ('Workshop Pengembangan SDM Kuartal II', 'Kegiatan', 'Program pelatihan intensif bagi seluruh karyawan telah berhasil dilaksanakan dengan antusias dan sambutan luar biasa.', '📚', 'published', '15 Jun 2025');

insert into gallery (title, icon, descr) values
  ('Rapat Direksi Tahunan', '👔', 'Rapat tahunan direksi dan manajemen'),
  ('Workshop Tim 2024', '📚', 'Pelatihan dan pengembangan tim'),
  ('Peresmian Kantor Baru', '🏢', 'Peresmian kantor cabang'),
  ('Penghargaan Nasional', '🏆', 'Momen penerimaan penghargaan'),
  ('Team Building', '🤝', 'Kegiatan team building karyawan'),
  ('Peluncuran Produk', '🚀', 'Event peluncuran layanan baru');

insert into services (icon, title, descr) values
  ('📋', 'Konsultasi Bisnis', 'Analisis mendalam dan strategi bisnis yang tepat sasaran untuk memaksimalkan pertumbuhan perusahaan Anda.'),
  ('📊', 'Manajemen Proyek', 'Pengelolaan proyek secara profesional dari perencanaan hingga pelaksanaan dengan hasil terukur.'),
  ('🔧', 'Solusi Teknis', 'Tim teknisi berpengalaman siap memberikan solusi teknis terbaik sesuai kebutuhan spesifik klien.'),
  ('📈', 'Pengembangan SDM', 'Program pelatihan dan pengembangan sumber daya manusia yang terstruktur dan berkualitas tinggi.'),
  ('🛡️', 'Audit & Kepatuhan', 'Layanan audit menyeluruh untuk memastikan operasional bisnis Anda berjalan sesuai regulasi.'),
  ('🌐', 'Transformasi Digital', 'Membantu bisnis Anda beradaptasi dan berkembang di era digital dengan teknologi mutakhir.');

-- Matikan RLS (Row Level Security) karena akses lewat server function pakai service_role key
alter table news disable row level security;
alter table gallery disable row level security;
alter table services disable row level security;
